"""MemoryStore protocol — the contract every storage backend implements.

Backends: SqliteStore (default, zero-config) and PostgresStore (pgvector).
Selected by create_store() from ZANII_DATABASE_URL.
"""
from __future__ import annotations

from typing import Any, Protocol

from ..types import MemoryRecord


class MemoryStore(Protocol):
    vec_enabled: bool

    # L0 conversations
    def record_l0(
        self, session_key: str, role: str, content: str, timestamp: int | None = None, session_id: str = ""
    ) -> int: ...
    def get_l0_after(self, session_key: str, after_id: int, limit: int = 200) -> list[dict[str, Any]]: ...
    def get_l0_before(self, session_key: str, before_id: int, limit: int = 6) -> list[dict[str, Any]]: ...
    def search_l0(self, query: str, limit: int = 10, session_key: str | None = None) -> list[dict[str, Any]]: ...
    def get_all_l0(self) -> list[dict[str, Any]]: ...
    def l0_exists(self, session_key: str, role: str, content: str, timestamp: int) -> bool: ...

    # L1 memories
    def insert_l1(self, record: MemoryRecord, embedding: list[float] | None = None) -> int: ...
    def l1_content_exists(self, content: str) -> bool: ...
    def count_l1(self) -> int: ...
    def get_all_l1(self) -> list[dict[str, Any]]: ...
    def get_l1_filtered(
        self,
        type: str | None = None,
        scope: str | None = None,
        created_before: int | None = None,
        limit: int = 100,
    ) -> list[dict[str, Any]]: ...
    def delete_l1(self, ids: list[str]) -> int: ...
    def mark_superseded(self, old_ids: list[str], new_id: str) -> int: ...
    def find_near_duplicate_pairs(self, max_distance: float) -> list[tuple[str, str]]: ...
    def keyword_search_l1(
        self,
        query: str,
        limit: int = 10,
        type: str | None = None,
        since: int | None = None,
        until: int | None = None,
    ) -> list[dict[str, Any]]: ...
    def vector_search_l1(self, embedding: list[float], limit: int = 10) -> list[dict[str, Any]]: ...
    def hybrid_search_l1(
        self,
        query: str,
        embedding: list[float] | None = None,
        limit: int = 5,
        type: str | None = None,
        since: int | None = None,
        until: int | None = None,
    ) -> list[dict[str, Any]]: ...
    def nearest_l1_distance(self, embedding: list[float]) -> float | None: ...
    def audit(self, op: str, detail: str) -> None: ...
    def get_audit(self, limit: int = 100) -> list[dict[str, Any]]: ...

    # Pipeline state / metadata
    def get_pipeline_state(self, session_key: str) -> dict[str, int]: ...
    def set_pipeline_state(self, session_key: str, watermark: int, pending: int, threshold: int) -> None: ...
    def get_kv(self, key: str) -> str | None: ...
    def set_kv(self, key: str, value: str) -> None: ...

    def stats(self) -> dict[str, Any]: ...
    def close(self) -> None: ...
